### ISSUE TITLE
How do I use a non swagger upstream?

### ISSUE THREAD

**Issue by russmac** [RetailMeNot/shield#3]
I've tried using "RawUpstreamService" I found in the code, which gets rid of the Exceptions from no swagger endpoints on the upstream. However the upstream never becomes healthy.

Is it necessary to setup swagger (on the upstream) endpoints for an upstream to work?

All my non Shield endpoint requests respond with a 404.

Looking at the spec, it seems only swagger(1|2) are supported as service types?
`https://github.com/RetailMeNot/shield/blob/fa8e0af212bd90efea4ab26ab1f896a67c15330f/src/test/scala/shield/actors/config/upstream/S3UpstreamUpdaterSpec.scala`

Did you guys have a recommended swagger plugin for ES? I was looking at this so far : https://github.com/timschlechter/swagger-for-elasticsearch *Just noticed this wont work with 5.x.x so wont be using it*

**Comment by russmac** [comment]
I might be doing this wrong, I have my upstreams as an elasticsearch cluster.
Is the intended upstream a swagger2 micro service that documents the elasticsearch cluster?

**Comment by talton-rmn** [comment]
> Is the intended upstream a swagger2 micro service that documents the elasticsearch cluster?

Yes.

ElasticSearch by itself does not expose swagger documentation for its endpoints.  While you could add swagger docs (via an ES plugin or other clever means) that describe all the ES endpoints, putting that setup behind Shield would effectively expose your entire ES instance.  

Typically you want more fine grained control over the access to the ES API, which probably means a dedicated service for wrapping ES.  This service would have Swagger docs and be the "upstream" service to Shield. 

> I've tried using "RawUpstreamService" I found in the code, which gets rid of the Exceptions from no swagger endpoints on the upstream. However the upstream never becomes healthy.

I'm curious how you did this.  Did you set `serviceType` to `RawUpstreamService` in your [configuration](https://retailmenot.github.io/shield/docs/0.2/upstream/), or were you hacking around in Shield code directly?  If the former, it _should_ have error'd since that's not a currently recognized service type.

**Comment by russmac** [comment]
@talton-rmn Thanks for the reply.
It did actually error but via a WARN rather then an error so I missed it. I saw the rawupstreamservice in the code and thought it was worth a shot as its naming described what I wanted. Obviously not the way to do it though. Your spec tests were helpful in figuring that out.

Unfortunately all the swagger1/2 plugins for ES seem to be outdated.

**Comment by talton-rmn** [comment]
Not a problem. Thanks for your interest in Shield.

There's probably a good use case for adding a new `serviceType` to Shield along the lines of a `CatchAll` service.  It wouldn't have to actually fetch any Swagger docs (meaning you wouldn't need your ES plugin), and would just presume that the service location can respond to `*`.
